# Generated by Django 3.1.3 on 2020-12-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('price', models.TextField(verbose_name='')),
                ('summary', models.TextField(default='Default test')),
            ],
        ),
    ]
