# Generated by Django 3.1.3 on 2020-12-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_uploads',
            name='image',
            field=models.ImageField(default='products/chairman.png', upload_to='products/'),
        ),
    ]
