# Generated by Django 3.1.3 on 2020-12-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_upload', '0002_auto_20201203_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_uploads',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=11),
        ),
    ]
